const LEAD_STATUS = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  QUALIFIED: 'QUALIFIED',
  DOCUMENTS_PENDING: 'DOCUMENTS_PENDING',
  APPLICATION_STARTED: 'APPLICATION_STARTED',
  SUBMITTED_TO_LENDER: 'SUBMITTED_TO_LENDER',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  DISBURSED: 'DISBURSED',
  CLOSED: 'CLOSED',
  NOT_INTERESTED: 'NOT_INTERESTED'
};

const LOAN_TYPES = {
  PERSONAL_LOAN: 'personal-loan',
  BUSINESS_LOAN: 'business-loan',
  HOME_LOAN: 'home-loan',
  LOAN_AGAINST_PROPERTY: 'loan-against-property',
  CAR_LOAN: 'car-loan',
  EDUCATION_LOAN: 'education-loan',
  GOLD_LOAN: 'gold-loan',
  DEBT_CONSOLIDATION: 'debt-consolidation',
  OTHER: 'other'
};

const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  SALES_MANAGER: 'SALES_MANAGER',
  SALES_EXECUTIVE: 'SALES_EXECUTIVE'
};

const LEAD_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
};

const LEAD_SOURCE = {
  GOOGLE_ADS: 'google_ads',
  FACEBOOK: 'facebook',
  INSTAGRAM: 'instagram',
  ORGANIC: 'organic',
  DIRECT: 'direct',
  REFERRAL: 'referral',
  WHATSAPP: 'whatsapp',
  OTHER: 'other'
};

const AUDIT_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LEAD_CREATED: 'LEAD_CREATED',
  LEAD_UPDATED: 'LEAD_UPDATED',
  LEAD_ASSIGNED: 'LEAD_ASSIGNED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  NOTE_ADDED: 'NOTE_ADDED',
  FOLLOWUP_CREATED: 'FOLLOWUP_CREATED',
  PRODUCT_CHANGED: 'PRODUCT_CHANGED',
  FORM_FIELD_CHANGED: 'FORM_FIELD_CHANGED',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED'
};

module.exports = { LEAD_STATUS, LOAN_TYPES, USER_ROLES, LEAD_PRIORITY, LEAD_SOURCE, AUDIT_ACTIONS };
